/// <reference types="cypress" />
describe('Registration suite', () => {
    beforeEach(() => {
        cy.log('Visit URL')
        cy.visit('https://business.staging.v2.workerhero.com/auth')
    })
    it('Register with valid credentials', () => {
        cy.wait(2000)
        cy.log('Click on register button')
        cy.wait(2000)
        cy.get('.nav > :nth-child(2)').click();
        cy.wait(2000)
        cy.log('Enter first name')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Name"]').type('QA')
        cy.wait(2000)
        cy.log('Enter last name')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Surname"]').type('Test')
        cy.wait(2000)
        cy.log('Enter email')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Email"]').type('areejouerghi2@gmail.com')
        cy.wait(2000)
        cy.log('Enter phone number')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Phone"]').type('52668548')
        cy.wait(2000)
        cy.log('Enter password')
        cy.wait(2000)
        cy.get('input[type="password"][placeholder="Password"]').type('Sido1234')
        cy.wait(2000)
        cy.log('Repeat password')
        cy.wait(2000)
        cy.get('input[type="password"][placeholder="Repeat password"]').type('Sido1234')
        cy.wait(2000)
        cy.log('Click on continue button')
        cy.wait(2000)
        cy.contains('Continue').click();
        cy.wait(2000)
        cy.log('Enter company name')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Name"]').type('QA Test')
        cy.wait(2000)
        cy.log('Enter company address')
        cy.wait(2000)
        cy.get('.address-input > .wh-s-input--container > .wh-s-input').type('Tunis')
        cy.wait(2000)
        cy.log('Select professional field')
        cy.wait(2000)
        cy.get('.professional-field-input > .dropdown-container > .zero > .ng-select-container > .ng-arrow-wrapper').click();
        cy.wait(2000)
        cy.log('Select company size')
        cy.wait(2000)
        // Select the dropdown and click to open it
        cy.get('wh-s-dropdown').click({ multiple: true });
        cy.wait(2000)
        // Locate the desired option and click to select it
        cy.contains('50-250').click();
        cy.wait(2000)
        cy.log('Agree to terms and conditions')
        cy.wait(2000)
        cy.get('input.wh-s-checkbox').check().should('be.checked');
        cy.wait(2000)

    })
    it('Register with invalid credentials', () => {
        cy.wait(2000)
        cy.log('Click on register button')
        cy.wait(2000)
        cy.get('.nav > :nth-child(2)').click();
        cy.wait(2000)
        cy.log('Enter first name')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Name"]').type('QA')
        cy.wait(2000)
        cy.log('Enter last name')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Surname"]').type('Test')
        cy.wait(2000)
        cy.log('Enter email')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Email"]').type('example.gmail.com')
        cy.wait(2000)
        cy.log('Error message should appear')
        cy.wait(2000)
        cy.contains('Email is not valid').should('be.visible'); 
        cy.log('Enter phone number')
        cy.wait(2000)
        cy.get('input[type="text"][placeholder="Phone"]').type('5266854852668548')
        cy.wait(2000)
        cy.log('Enter password')
        cy.wait(2000)
        cy.get('input[type="password"][placeholder="Password"]').type('123')
        cy.wait(2000)
        cy.log('Repeat password')
        cy.wait(2000)
        cy.get('input[type="password"][placeholder="Repeat password"]').type('1234')
        cy.wait(2000)
        cy.log('Error message should appear')
        cy.wait(2000)
        cy.contains('Passwords do not match!').should('be.visible');
        
    })
})